### ISSUE TITLE
[FEATURE] Have Font-Size and Font-Weight adjustable via settings

### ISSUE THREAD

**Issue by TimSusa** [TimSusa/midi-sliders#11]

**Comment by TimSusa** [comment]
Is supposed to be fixed by: 2de088e2d5e9471a371023d990e864ae75d84912

**Comment by alectroniq** [comment]
works fine now, thanks! some more things to fix: 
1. can we accomplish an always centered position of all labels, vertically and horizontally? 
there seems to be a margin on top of every label - so by increasing the font size, the label slips down and starts to run out of the button itself. 
2. font-weight would be nice to have
3. can we accomplish font-size and font-weight on sliders, too?

**Comment by TimSusa** [comment]
Ok have adjustable font-weight established by this commit: https://github.com/TimSusa/midi-sliders/commit/a3389a5f3703507d3f4c4ce944d2f43ba3d05965

at next working on having that on sliders too

**Comment by TimSusa** [comment]
can you provide me with a video for problem 1? I cannot get that.

**Comment by TimSusa** [comment]
Established font settings for sliders too: https://github.com/TimSusa/midi-sliders/commit/f491a77764a9e6b6645ed21712fb5a9a3cb10a94

**Comment by alectroniq** [comment]
problem 1 is solved now, somehow :)
