### ISSUE TITLE
[FEATURE] stepping through pages

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#20]
A new page component has to be established, which works like an anker.
Technically it should contain an ID at the DOM element, which can be scrolled into view with element.scrollIntoView()
A footer has to be introduced, where a page button is added, as soon as a page component is created. After pressing the button the page is shown.

**Comment by TimSusa** [comment]
Feature was pushed. Need additional feedback, if we can close this issue.
