### ISSUE TITLE
[BUG] shortkeys don't work on Windows

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#21]
no reaction on any of the ctrl+... commands

**Comment by TimSusa** [comment]
Switched to alt keys.

**Comment by alectroniq** [comment]
ALT keys don't work on Windows, too :-/

**Comment by TimSusa** [comment]
Try to get along with this fix on usage of shift button: c05dffcb324a2595772f5d4057462089d6aad9e1

**Comment by alectroniq** [comment]
shortkeys don't work with SHIFT button, too
(Windows, Chrome)

**Comment by TimSusa** [comment]
That drives me nuts!

**Comment by TimSusa** [comment]
Should now be fixed with https://github.com/TimSusa/midi-sliders/commit/6b23846497ccae3e134d1cbdc5d3c3de956db80e because now we are listening for the key address. Please check in webapp

**Comment by alectroniq** [comment]
works finally, thanks so much! sorry for Windows generally :-D

**Comment by alectroniq** [comment]
indeed we now have the problem, that you can't label elements with CAPS containing the shortcut letters S, P, L, V and T 
:(

**Comment by TimSusa** [comment]
I would say this is fixed now: https://github.com/TimSusa/midi-sliders/commit/5ea6b2cd8f4a6b254bee365fa553fe77705b504d

**Comment by alectroniq** [comment]
test positive, thanks!

**Comment by TimSusa** [comment]
I remove the key event listeners as soon as you open up the settings of an element. When settings close, I add the listener. This is desired behaviour. We have to find the case, when the listener is removed (unwanted).
