### ISSUE TITLE
[FEATURE] establish transparency in label colors

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#25]
when a label is used as a page anker or as an empty space (place holder), then it should be possible to make it disappear with transparency settings on background-color and font-color.
AND/OR: a checkbox "invisible"

**Comment by TimSusa** [comment]
@alectroniq: Fix was provided by commit: https://github.com/TimSusa/midi-sliders/commit/ead6746b30bed20132584e303fa5ddcb1d8ec722

Can you please test that at the webapp?

**Comment by alectroniq** [comment]
works fine!
besides: no heavy CPU load detected during quick & crazy color-picking-madness
