### ISSUE TITLE
[FEATURE] Handle crossplattform understanding of saved presets

### ISSUE THREAD

**Issue by TimSusa** [TimSusa/midi-sliders#28]
A preset, which was saved at win, should be readable on a mac system

**Comment by alectroniq** [comment]
[test save.zip](https://github.com/TimSusa/midi-sliders/files/2437903/test.save.zip)
saved from WebApp at Win10 (64)

**Comment by TimSusa** [comment]
Established an commit, where other presets can be loaded, but if the driver is not known, you have to chose it for each element. https://github.com/TimSusa/midi-sliders/commit/d690d66d204257bef4b22a22222e01714814e0d4
