### ISSUE TITLE
[BAD] Presets are downloaded as json.txt (Win)

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#30]
ist it possible to create .json files?

**Comment by TimSusa** [comment]
In my opinion this is not a bug, since it does not introduce any malfunction behaviour and is not introduced due to some wrong code.  We can look towards a feature, where a file dialog is presented. This is not that easy for chrome, but I will have a look.

**Comment by alectroniq** [comment]
works fine, thanks!

**Comment by alectroniq** [comment]
just a note - chrome shows the following message:
![save js preset - chrome warning](https://user-images.githubusercontent.com/43702087/46936277-31742a80-d05e-11e8-89fe-def98149acf3.JPG)
but saving and loading presets works fine though.
