### ISSUE TITLE
[FEATURE] establish a "show/hide CC value" setting on sliders

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#32]
as the slider's position represents it's current value, it's not necessary to display a number below. 
but it'd be good to have it optional via a hide/show setting in the settings menu.

**Comment by TimSusa** [comment]
This should be possible without any breaking changes for your presets.

**Comment by TimSusa** [comment]
Established by https://github.com/TimSusa/midi-sliders/commit/96013003210b1051a7d8a4b608b873a4dad20914

**Comment by alectroniq** [comment]
this works. 
but the reason therefor was to free some space, but now this creates more ununsed space. 
expected behaviour: as the value is hidden, the slider size should increase vertically to the frame border
experienced behaviour: as the value is hidden, the slider size even decreases vertically. so now there's even more empty space where the value was shown before.

**Comment by alectroniq** [comment]
only the vertical one

**Comment by TimSusa** [comment]
this should be fixed with: https://github.com/TimSusa/midi-sliders/commit/50b08f3c4cf3dfd6af4c9de95eaea072c4b09850

**Comment by alectroniq** [comment]
fine, but this now causes another minor problem: 
on vertical sliders the space between the slider and its label is too tight (just a few pixels), so the slider overflows the descenders of the letters.

**Comment by TimSusa** [comment]
Same here. Feature is established. Please create another ticket for this.
