### ISSUE TITLE
[FEATURE] establish 2 operation modes: Performance / Edit

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#34]
**Performance Mode** frees some space and avoids inadvertent Preset modifications:
- Settings Mode and Layout Mode not accessable
- Menu bar on top is hidden
(in WebApp: hide as much browser bars and options as possible) 

**Edit Mode:** 
- access Layout Mode and Settings Mode
- switch Themes
- load/save Presets

**Comment by TimSusa** [comment]
Therefore we should define a keyboard shortcut and a small icon on the UI, where you can switch between modes.

**Comment by TimSusa** [comment]
Established with https://github.com/TimSusa/midi-sliders/commit/6b23846497ccae3e134d1cbdc5d3c3de956db80e

Try switching with shift+p

**Comment by alectroniq** [comment]
works fine, thanks!

**Comment by alectroniq** [comment]
the only way to escape the Live Mode, is Ctrl+P. but you can't see any command for this. so we should:
- either include a small button to escape live mode
- or maybe just note a hint in the upper right corner, like "Esc: Ctrl+P" or similar

**Comment by TimSusa** [comment]
Would you please go and create new issues for new feature wishes?
