### ISSUE TITLE
[FEATURE] establish slider + label colors

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#39]
integrate color picking options also to the slider settings

**Comment by TimSusa** [comment]
Technically this should be possible, but I propose a lot of fiddling around with CSS/JSS, which will take a lot of effort.

**Comment by alectroniq** [comment]
OK this is not too important. better first get the basic functionality done.

**Comment by alectroniq** [comment]
in the meantime it would also help, to make color settings for the slider's labels available (just like on the buttons). later, when slider colors are implemented, you can still keep the label-color feature.

**Comment by TimSusa** [comment]
should be established
