### ISSUE TITLE
[BUG] settings: color picker states not correct (transparency)

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#40]
in settings mode: when opening the color picker of an element, it doesn't show the exact color settings, that it already has. especially the transparency settings shows another value.

**Comment by TimSusa** [comment]
That sounds strange to me, because I took a lot of effort to handle this. Are you able to reproduce this? If yes, only webapp or electron app and webapp?

**Comment by alectroniq** [comment]
https://we.tl/t-czLw6BmSYD
video in german. sorry for the blurriness!

**Comment by TimSusa** [comment]
Fixed with: https://github.com/TimSusa/midi-sliders/commit/2145134234228e0913619f7d5eabc6c92aab49ce

**Comment by alectroniq** [comment]
test positive

**Comment by alectroniq** [comment]
test positive (chrome)
