### ISSUE TITLE
[FEATURE] establish CC range settings

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#41]
in the settings of Sliders and CC Buttons it should be possible to define the range of the output values.
for instance _FROM 0 TO 127_ or _FROM 85 TO 23_
for sliders this means, that it's input is not limited to these values, but the output is values are scaled to them. i hope that's comprehensible. this is common practice for every MIDI device these days.

**Comment by TimSusa** [comment]
I think it would be possible, but: It will give you a breaking change of presets, I guess and It will take a middle lot of effort.  Would be ok for me..

**Comment by alectroniq** [comment]
sorry for my laymanship: isn't it easy math, just to scale a value?

anyway - if this breaks exsiting presets, this is a blocker. so we need the decision now: implement or not? 
**con:** in many DAWs you can find a workaround to scale the values. 
**pro:** I don't know any hardware device with this ability.

so even if I personally don't need it right away, I think this will be a must-have one day.
and if it breaks presets, we'd have to implement it **now** :-/

**Comment by TimSusa** [comment]
now i understand.. sry, you just only want output range for the values. OK, you want a minimal and a maximal value ? I think i can build that without breaking changes.

**Comment by TimSusa** [comment]
Adressed by: https://github.com/TimSusa/midi-sliders/commit/a5489526981c6ed377953f2a509b23c1c58f4a73

**Comment by alectroniq** [comment]
works great, thanks so much!

big sorry for reopening, but to complete the whole thing, we should also integrate these range settings to all types of buttons. there you'd define the sent values for ON and OFF, with the following standard values (like they already are now)...
CC buttons: ON = 127, OFF = 0
NOTE buttons (via velocity): ON = vel 127, OFF vel = 0

**Comment by TimSusa** [comment]
Would you please create a new ticket for this. I would like to have nice little issues.
