### ISSUE TITLE
[BUG] driver selection not availlable in newer version

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#47]
I'm not sure if this is already sorted out completely in the new versions. But for understanding I document the following issue: 
1. in version 0.1.0 a preset was created, drivers were selected
(driver option "none" was not available yet in v0.1.0, this was implemented from v0.2.0)
2. opening this preset in the current Web App version (conform to v0.4.0) results in false driver selections
3. i fixed the driver selections in the current Webn App and saved the new preset
4. loading this new fixed preset works fine, driver selection is correctly saved
5. test: loading the old preset (see 1.) in Web App or Electron App v0.1.0 leads to wrong driver selections
6. repeating test 4., works fine

**Comment by TimSusa** [comment]
Obviously, this feature leads to a breaking preset change, where I did not expected it. Using new versions, (you have to wait until i have fixed elektron build chain) with none driver should work fine in the future, so this Blocker will disappear automatically, I would say.

**Comment by TimSusa** [comment]
Should all be fixed by using straightforwardly 0.4.3

**Comment by alectroniq** [comment]
My preset that was saved under v0.4.0 and loaded in v.0.4.4 had the same issue. 
So if you say it's fixed from 0.4.3, I'll have to see, if my 0.4.4 preset is loaded correctly in future versions.
If not, this will be pain in the ass for any update and Auto-Update...
