### ISSUE TITLE
[FEATURE] establish undo/redo

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#51]
Especially in Auto Arrange Mode you can crash your entire work within a millisecond with one wrong move. If you haven't saved directly before, you gotta start all over again. 
Is undo/redo hard to implement? (of course not in performance mode)

**Comment by TimSusa** [comment]
Hey, ok I have found this: https://github.com/omnidan/redux-undo

If I succeed to use this library, it will be not that hard to provide undo/redo

**Comment by TimSusa** [comment]
As a first mvp we have jump back by shift - z. This helps, when fiddling arround in layout mode where all seems to be broken. https://github.com/TimSusa/midi-sliders/commit/e99d1838970d01d18be3741fefc4934ca62f9b45
