### ISSUE TITLE
[BUG] ElectronApp: debugger shows missing internet connection

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#52]
![img_20181101_120641](https://user-images.githubusercontent.com/43702087/47848563-08c69180-ddcf-11e8-9ed2-951070683ed2.jpg)
while not connected to the internet (as supposed on stage) the Electon App shows this debugger error

**Comment by alectroniq** [comment]
Again today: 
[Internet Disconnectted -1543422210509.log](https://github.com/TimSusa/midi-sliders/files/2626113/Internet.Disconnectted.-1543422210509.log)
But during rehearsal everything did fine.

**Comment by TimSusa** [comment]
Should be fixed with midi-bricks-mono
