### ISSUE TITLE
[BUG] footer pages order not saved in preset

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#53]
In the footer the pages order is not saved in my preset. A loaded preset always has a different order, than I saved it. 

BUT:
- close App and reopen it (without loading preset): order remains correct

**Comment by TimSusa** [comment]
Should be fixed with: https://github.com/TimSusa/midi-sliders/commit/0dd390d13fcc9fc1978614a5494d6965a9b5ae9d
