### ISSUE TITLE
[FEATURE] footer: page button colors

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#54]
to keep a clear view about a performance, it's essential to work with a color code. 
for this the pages buttons shall be colorizable.

**Comment by TimSusa** [comment]
Wouldn´t it be enough, to just show the same color, which is already set in the page element?

**Comment by alectroniq** [comment]
yes indeed! already wanted to mention this. but in this case it should not use the transparency setting (in order not to disappear, if a page label is blended out).

**Comment by alectroniq** [comment]
established in v1.7.0
