### ISSUE TITLE
[BUG] display error on slim sliders

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#55]
when scaling a horizontal slider to minimum height, it gets partly overflown by other elements.
This is what it looks like... (note the "rev decay" and "delay amount" sliders)

....in Layout Mode: ![img_20181101_161125](https://user-images.githubusercontent.com/43702087/47860614-391f2780-ddf1-11e8-939e-4340fe6f41cd.jpg)

...in Performance Mode (and similar in Settings Mode): 
![img_20181101_161116](https://user-images.githubusercontent.com/43702087/47860682-6b308980-ddf1-11e8-9324-f08cf86f01c4.jpg)

(Electron App, Win)

**Comment by TimSusa** [comment]
Can you please provide me with that preset (dropbox or here)?

**Comment by alectroniq** [comment]
example preset:
[horizontal slider example.zip](https://github.com/TimSusa/midi-sliders/files/2543349/horizontal.slider.example.zip)

**Comment by TimSusa** [comment]
should be fixed
