### ISSUE TITLE
[BUG] page button has not its anker's name

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#61]
This worked before 0.5.0 or even 0.4.x. 
Now adding a new page + labeling its anker doesn't cause it's footer button to be renamed. It remains for instance "PAGE 47".

**Comment by TimSusa** [comment]
Fixed with : https://github.com/TimSusa/midi-sliders/commit/ae2f192a0ef50182217245d02f3e24f3f2522acf
