### ISSUE TITLE
[FEATURE] option: hide scrollbars in perfomance mode

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#62]
in Performance Mode there is still appearing a big scrollbar on the right side.
an optional show/hide setting would be fine for this mode

**Comment by TimSusa** [comment]
This is not possible, and scrollbar should disappear in performance mode. This is fixed with https://github.com/TimSusa/midi-sliders/commit/55ca83e87f320b608afe222b9827f2806dae4e41

**Comment by alectroniq** [comment]
test positive
