### ISSUE TITLE
[BUG] slider range: value 0 not possible

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#63]
even though the standard setting of the sliders is max 127 and min 0, it is not possible to set any of both values to 0. it automatically changed to a 1. 
this issue exists on both horizontal and vertical sliders.

**Comment by TimSusa** [comment]
Fixed with: https://github.com/TimSusa/midi-sliders/commit/a8bba8e8d88741733b78d0ede40f5d2205d01358
