### ISSUE TITLE
[FEATURE] CC listener: MIDI channel selector missing

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#64]
it's possible to define the MIDI channel for the MIDI out,
but there is no MIDI channel selector for the MIDI in listener. 
this is badly needed.

**Comment by TimSusa** [comment]
Adressed by https://github.com/TimSusa/midi-sliders/commit/2d7b7385b22ecd9f101e81fc3ac0373e4bef28c9

**Comment by alectroniq** [comment]
works!
