### ISSUE TITLE
[BUG] CC listener: jittery and slow behaviour

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#65]
this is for the MIDI feedback function: 
on a slider incoming MIDI data (selected via CC listener) is displayed very slowly or jittery. 
(outgoing MIDI data reaches the respective device quick and clear, just as intended)

i think the problem might be, that incoming MIDI data is directly or indirectly passed to the output again: 
it seems that a slider is receiving a value, taking place on this position and finally puts it out as a MIDI value again. during this time period the data source has already sent out new values, but is interrupted by the incoming values from its destination - so this leads to a back-and-forth, causing this jittery, slow behaviour. it's kind of a delayed MIDI loop. 
there sould be a gate, that avoids incoming data to be put out right away. 
hope my description is comprehensible.

**Comment by alectroniq** [comment]
in english this time ;)
[https://we.tl/t-3cWagJHnF2](url)

I'm sure, there is no second parallel signal. Also this behaviour is way beyond the normal latency.

**Comment by TimSusa** [comment]
I am really unsure, why this is a blocker for you. It is just a little slow, but does what it is supposed to do , or? I can try to get rid of the debouncer for the midi input, maybe the slider is more quick after that.

**Comment by TimSusa** [comment]
disabled debouncer with https://github.com/TimSusa/midi-sliders/commit/0ebca6f6708989d2d30fa0c79ce8387c23a80083

**Comment by alectroniq** [comment]
not solved yet. but i have more detail for you: 
_very slow_ movements on the hardware are traced _without_ that latency. 
as soon as you turn hardware knobs more quickly, the app's slider movement gets interrupted and gradually reaches its final position with 1-2 seconds latency (almost 1 bar in musical dimensions, so this precludes real musical performance - that's why this is so important). 

**test**: in Ableton the same MIDI data from the same device is traced immediately, without any additional latency or interruptions. so in my understanding there must be a bug.

another fact: I've had similar problems on the _Emulator_ software (that one we're trying to beat here). this was caused by MIDI feedback, like described in my assumption in the first post above. 

>> can you code kind of a lock or gate, that says?: 
as long as a slider is controlled by incoming MIDI (via its listener), do not output MIDI data.
only output MIDI data, when the slider is controlled by the interface (touch or mouse).

**Comment by TimSusa** [comment]
Please note: If a midi message arrives, i do only update the state. I do not send any additional midi message outside. See code here:

```
  [ActionTypeSliderList.MIDI_MESSAGE_ARRIVED] (state, action) {
    const sliderList = state.sliderList.map(item => {
      const { listenToCc, midiChannelInput } = item
      if (listenToCc && listenToCc.length > 0) {
        const { val, cC, channel } = action.payload
        const haveChannelsMatched = (midiChannelInput === 'all') || channel.toString() === midiChannelInput
        const hasCc = listenToCc.includes(cC && cC.toString())
        if (hasCc && haveChannelsMatched) {
          const { colors } = item
          const { colorActive, color } = colors
          return { ...item, val, colors: { color: colorActive, colorActive: color } }
        } else {
          return { ...item }
        }
      }
      return { ...item }
    })
    return { ...state, sliderList }
  },
```

**Comment by alectroniq** [comment]
I noticed the following: 
In an empty layout I create a slider and map it to control my hardware and listen at the same Ch. and CC - this runs super quick, direct and smooth. 
When I create more and more elements, it's getting more and more jittery. On my system it starts getting dropouts and jitters from around 25-30 elements, hardly depending on sort of elements. 
There is also no dependence on my general current CPU load!

As mentioned before, the MIDI outputs work smooth and direct, just the listened values are displayed this hacked way. 
So I assume a performance issue either at the MIDI listeners or at the graphic display in Chrome or whatever.

**Comment by alectroniq** [comment]
Test notes: on my high performance studio PC (Intel Core i9-7900X with 10 cores, Nvidia GeForce GTX1050ti) this issue begins from around 55-60 elements. In a live performance this is a reasonable amount of MIDI Controllers. 

If we can't improve allover performance: 
Maybe we should think about splitting a preset/layout into real pages? Like having a classic website navigation with sub pages? Because I think the reason for the performance issue is, that we're now scrolling one huge layout and just navigate thru it by ankers.

**Comment by alectroniq** [comment]
Using the new MIDI Driver Settings and filtering only those Drivers, Channels, CC/Notes - is awesome! So The listener performance has greatly improved now. 
Filtering is also super important to avoid interferences with Drivers used in other applications!

I noticed, that directly after a Browser Refresh the performance seems perfect, but after some work it slowly declines. Maybe this has to do with editing my preset. But it's still better than before. 

Also when you're moving several external Elements in parallel, performance gets very unsmooth again. 

I compared with _Emulator_, whose performance is still a bit better on Inputs. I guess this is, because in Emulator a Preset is split in real pages, like mentioned above. Not as we have: one single page, that is just scrolled. 

For further considerations: 
- We spoke about selective interface-rendering of only the cutout that's currently shown in the window.
- IMO smooth scrolling through a Layout is actually not necessary in such an App. So we could do hard switches.

**Comment by alectroniq** [comment]
**new important idea:**
Entering Live Mode should disable all Layout and Editing capabilities in the background and cut down the entire program functionality to only the pure MIDI controlling and switching pages.

**Comment by alectroniq** [comment]
Right now single sliders controlled by external MIDI hardware via CC listener run pretty smooth also in crowded layouts - under the condition that only certain drivers and channels are selected in MIDI Driver Settings. 
As soon as several Sliders receive and display incoming data at once, movements get rugged again. 
For me this is fine for now. Maybe it should be improved in the future, if requested by many users.
