### ISSUE TITLE
[BUG] driver selection corrupted, when adding new device to the setup (WIN)

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#66]
I created a preset with a certain MIDI setup and saved it with the Electron App v0.8.0. Now I plugged in another MIDI device via USB (Circuit Mono Station) and started the Electron App 0.8.0. All elements now have the wrong driver selected: the one above the desired one in the selection list. Reloading the preset doesn't help. The debugger doesn't show errors. 

Test: unplugging the device and opening the App again now loads the correct driver selections.

**Comment by TimSusa** [comment]
As worst case, it is about the Operationsystem, which changes all the driver IDs, when you plugin another midi device. I think we should log out the driver id just before and after plugging in the device. hopefully, they stay the same, otherwise I should take care of the drivername additionally.

**Comment by TimSusa** [comment]
Anyway, in my opinion this is inconsistent behaviour of windows OS, on my mac I don´t have any issues with this. I am now supposed to create shaky code, which drives me nuts.

**Comment by alectroniq** [comment]
i know it's rather a Windows proplem, which also sometimes occures in other softwares. so if an automated solution for this is unreasonable, i think: 
let's at least display an error message on preset load, when a driver couldn't be found, that was saved in the preset. ideally straightly directed to Settings View with the elements highlighted (marked red), that weren't able to access their driver.

**Comment by alectroniq** [comment]
strange error on Chrome in Windows!
with my supposed, correct setup (all devices connected and ON) I opened the site and refreshed it. loaded my preset... worked. closed Chrome and turned 2 external MIDI devices OFF. reopened Chrome with the site and got this:
![webapp error](https://user-images.githubusercontent.com/43702087/48495597-a50d8100-e830-11e8-9c49-ad497e7706e8.JPG)
closing and reopening Chrome doesn't help, nor deletion of cookies is possible.

**Comment by alectroniq** [comment]
just to mention this, maybe this problem has another dimension: 
the external MIDI devices that I'm using (_Novation Circuit_ and _Novation Circuit Mono Station_) have a certain driver problem on Windows, that's causing BSODs with messages like "IRQL not less or equal" and similar, when connecting/deconnecting them, while they're accessed by a running system. 
_Novation_ knows this error and for now only recommends to use Windows' standard drivers instead of Novation's drivers - which is not an option for me, as I need certain functions of the Novation drivers. 

I'm not sure if these problems are interconnected, but better mentioned it.

**Comment by TimSusa** [comment]
What should I say ? ? The best would be, that all players in the game work with the official standards. Otherwise everything is complex. Anyhow, I will invest an double checked extra test run for this... Anyaynhow, you are free to close this...

**Comment by TimSusa** [comment]
Can you invest a test run without the problematic gear?

**Comment by alectroniq** [comment]
Sorry but I'm unable to do anything, because the App always opens up like my screenshow above is showing. Looks like a huge bug in the Web App.

**Comment by TimSusa** [comment]
do you got an error message from console?

**Comment by TimSusa** [comment]
I would claim this should be fixed with the very new version. Please reselect all drivers and save a new preset. Always refresh the browser after plugin in/out some hardware, then load the preset!

**Comment by alectroniq** [comment]
Plain documentation of opening the Web App today (without any knowledge, what's correlating with whatever circumstances): 
- tried to open Chrome browser on Windows normally: did not start up
- downloaded the recent Chrome Version 70.0.3538.102 and reinstalled the program on Win
- Chrome first opened with the faulty page [shown above](https://github.com/TimSusa/midi-sliders/issues/66#issuecomment-438721828)
- refresh, loaded the Web App normally and functional
- debugger shows only this message (new issue will be created for this): 
[midi-sliders.herokuapp.com-1542616410829.log](https://github.com/TimSusa/midi-sliders/files/2594394/midi-sliders.herokuapp.com-1542616410829.log)

**Comment by alectroniq** [comment]
**Despite this** I tested the driver selection savings: saved a preset with one device unplugged, loaded it with the device plugged and the saved drivers selections remained correct! 
So for know we can regard this as functional working and solved. Good job, thanks :)
