### ISSUE TITLE
[FEATURE] complete global settings list

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#67]
thanks for the the Global Settings View, this is very helpful! 
it would be perfect, if we could complete the following list columns for each element: 
- Note/CC#
- MIDI Channel
- saved state/value
- Listener: MIDI Channel

**Comment by alectroniq** [comment]
the position of the sliders and the states of the buttons, as they were saved in the preset. maybe like "last saved value" and "current value". but i think, both are a "nice to have" :)

**Comment by TimSusa** [comment]
https://github.com/TimSusa/midi-sliders/commit/216febe75f776be99a7a999d44e09566a45f1938

**Comment by alectroniq** [comment]
test: works.
Awesome, really really helpful, great work. Thanks! :)
