### ISSUE TITLE
[FEATURE] establish PGM change

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#68]
establish a "PGM Button" that sends out a definable PGM value from 0-127 including the following features: 

- driver selection
- channel selection (1-16, all)
- like in Ableton: include Bank, Sub Bank (which should include "none" options)

**Comment by TimSusa** [comment]
https://gph.is/28MzND8

**Comment by alectroniq** [comment]
Possibly PGM Change is selected by CC#32 and i think it's not a SysEx message. 
I think that a certain controller value can only be sent out once, so we should find a way to retrigger a message. This is because I regularly experience jittery, malfunctional reception of PGM change commands in several devices (when the commands are sent by Ableton). Still trying to figure out, why this happens. 
We should find a source for the fully explained [General MIDI](https://en.wikipedia.org/wiki/General_MIDI) standard.

**Comment by TimSusa** [comment]
Established by: https://github.com/TimSusa/midi-sliders/commits/master

**Comment by alectroniq** [comment]
This works just perfectly and super reliable on my Novation Circuits! In Ableton it doesn't work that reliable.
For now I don't necessarily need it, but we should integrate Banks and Sub Banks for other devices in the future.
