### ISSUE TITLE
[FEATURE] Make MIDI Feedback available

### ISSUE THREAD

**Issue by TimSusa** [TimSusa/midi-sliders#7]

**Comment by TimSusa** [comment]
in settings menu it should be adjustable, on which driver and cc address a value should be listened to, which should  only change the value of the slider, and does not send a further MIDI signal.

**Comment by alectroniq** [comment]
marked as a blocker, as I need this for my first live show with the App.
it's necessary for controlling external hardware, for proper interaction (syncronisation) of hardware controlled knobs and the App's sliders states (called "MIDI feedback").

**Comment by TimSusa** [comment]
Adressed by https://github.com/TimSusa/midi-sliders/commit/ce16f3df771c68b1de808a22c1b1ad63e600fd9f

**Comment by alectroniq** [comment]
Works!! happy little me :)
