### ISSUE TITLE
[BUG] debugger shows timeout message

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#70]
[-1541749778551.log](https://github.com/TimSusa/midi-sliders/files/2565694/-1541749778551.log)

see the last lines: 
> version:'10.0'
> main.5c79017e.js:1 [Violation] 'setTimeout' handler took 175ms
> [Violation] Forced reflow while executing JavaScript took 85ms

**Comment by TimSusa** [comment]
When did this occur? What did you do?

**Comment by alectroniq** [comment]
I could not reproduce it yet, but it seems to happen like about 1 of 8 times. I didn't have an internet connection. Maybe also my computer was very busy in the background, when I loaded the App. Right after restart I just loaded my Liveset into Ableton Live and Reason and then opened the App - maybe I was pushing too hard ;)

**Comment by alectroniq** [comment]
This actually occurs regularly, every time after system boot - doesn't matter if I wait after system boot or if I have any other applications running. 
[-1544544104794.log](https://github.com/TimSusa/midi-sliders/files/2668292/-1544544104794.log)

**Comment by TimSusa** [comment]
Should be fixed with new version
