### ISSUE TITLE
[BUG] Electron App 0.9.0: Live Mode vs. Global Settings / no escape

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#73]
The last time I closed the Electron App (coming from 0.8.0), it was in Live Mode and also possibly in the Global Settings (not sure). 
 
I opened the Electron App v0.9.0 today and only got this screen: 
![image](https://user-images.githubusercontent.com/43702087/48695974-e612e600-ebe0-11e8-94f4-bdbdffd7788e.png)
- it's impossible to leave Global Settings
- it's impossible to quit Live Mode via the shift+p command
- nor any other shortkey commands are working
- this relates to issue #45 
- this doesn't occur in the Web App

**Comment by TimSusa** [comment]
Shortkeys are not supposed to work in global settings. I just switch live mode to off, if going to global settings. Fixed by: https://github.com/TimSusa/midi-sliders/commit/eee0f1aa3285f978c0f3d6f806d11bee23da7fbf
