### ISSUE TITLE
[BUG] surface malfunction

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#74]
Big problem in Web App (equates Electron App 0.9.0), filmed here: 
[https://we.tl/t-vr3egggnRF](url)

**Description**
After reassigning all drivers in my preset:
- sliders won't move, **but** send out MIDI data correctly
- no visual feedback on the buttons
- buttons toggle ON works fine, toggle OFF not working

During filming the following debugger log was created: 
[midi-sliders.herokuapp.com-1542620266081.log](https://github.com/TimSusa/midi-sliders/files/2594644/midi-sliders.herokuapp.com-1542620266081.log)

Pls let me know if you need more data.

**Comment by TimSusa** [comment]
fixed with

**Comment by alectroniq** [comment]
fine now
