### ISSUE TITLE
[FEATURE] establish 14-bit slider

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#75]
for two purposes: 
- a pitch fader for DJing
- pitch bend control

I'm not into the technical background of the coding of 14-bit MIDI messages. But here's a first insight: 
[http://www.midibox.org/dokuwiki/doku.php?id=midi_specification#bit_midi_messages](url)

**Comment by TimSusa** [comment]
Cannot see a higher sense. Let us make nrpn
