### ISSUE TITLE
[FEATURE] move slider value onto slider track

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#79]
A slider's current value should appear right on the top end of a slider's track (right below its label). 

As shown in #78 (ignore here: the mark on the right and the saved value at the bottom): ![saved value](https://user-images.githubusercontent.com/43702087/48951847-5783c900-ef40-11e8-9b90-4629c677e5ab.png)
It's okay, if the slider's handle "slips under" the value, just as it does on a flat horizontal slider (as mentioned in #49 before).

Because then:
- Your finger doesn't cover the value, when controlling.
- The slider itself doesn't need to be resized when showing its value. 
- more space is saved.

**Comment by TimSusa** [comment]
Sry, this is very hard to implement, because you will try to put a DOM Element on Top of the slider, which will disrupt user input. I tried already to set display none on hover, but this label blinks.

**Comment by alectroniq** [comment]
What do you think? Should we just place the value in line 2 below the label? 
It's just for not to cover the value with the user's finger, which occurs in very most cases now.

**Comment by TimSusa** [comment]
You can just switch out of the settings/layout view, to hide the stuff... so  I would say 👎On the other hand, you requested the resetting feature...  To much CSS fiddling at the moment for my nerves...

**Comment by alectroniq** [comment]
okay, anyway priority for this is low right now.
