### ISSUE TITLE
[FEATURE] establish global value/state recall from saved values

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#80]
In Global Settings place a button next to the new column "Saved Value" (see #76):
"Recall all saved states"

**Comment by TimSusa** [comment]
Established by https://github.com/TimSusa/midi-sliders/commit/4c52c7b46943765b65fdeabfb7787e4687c8d6f1

**Comment by alectroniq** [comment]
Awesome! Works - thanks so much!
