### ISSUE TITLE
[BUG] cloned element corrupts layout and undo

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#81]
I experienced two strange behaviours with elements, that are cloned via the Clone command in Settings dialog: 
- the new clone is placed in the top left corner of the layout, **above** (in Z axis) the other elements. when moving the clone, there sometimes occurs a "layering" of elements in Z axis, they get stacked. 
generally a clone should be placed below the cloned source. 
- cloning seems to corrupt the Undo history somehow. When I pressed Shift+Z to undo the layout demolition (mentioned above), the Undo function led back about 10 Undo steps and undid changes from before cloning.

**Comment by TimSusa** [comment]
curropting layouts should be fixed

**Comment by alectroniq** [comment]
Yes, Layout corrupt fixed.
